// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa90SXO14olTdnYLirmeDzVno5VKcWe0o',
    appId: '1:427083718633:web:55675a5b38d51a8a9e7578',
    messagingSenderId: '427083718633',
    projectId: 'testproject-6c557',
    authDomain: 'testproject-6c557.firebaseapp.com',
    storageBucket: 'testproject-6c557.appspot.com',
    measurementId: 'G-W7RL2DZ69T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVNzJMobiYkcLFmu3Q6bfjdTm9n7QbDU',
    appId: '1:427083718633:android:6d0861dc453193a59e7578',
    messagingSenderId: '427083718633',
    projectId: 'testproject-6c557',
    storageBucket: 'testproject-6c557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxwpx2BaZHDTygeeErFeKtKE91vV62GTQ',
    appId: '1:427083718633:ios:713e84615e8cf2069e7578',
    messagingSenderId: '427083718633',
    projectId: 'testproject-6c557',
    storageBucket: 'testproject-6c557.appspot.com',
    iosClientId: '427083718633-vmr3f7f7ed09uv46mnlqle1o8dphmk0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
